server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
logging:
  level:
    org:
      zalando:
        logbook: trace
logbook:
  filter:
    form-request-mode: off
  format:
    style: http
chatgpt:
  api-key: ${API_KEY}
  max-tokens: 1000